# Docs for Azure Functions Core Tools: https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - flextest5601pyfa2

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Path to your function app project
  PYTHON_VERSION: '3.12'               # Python version to use

variables:
  system.debug: true
  agent.diagnostic: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read                     # Required for actions/checkout
      id-token: write                    # Required for azure/login OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Azure Functions Core Tools
        run: |
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-4

      - name: Resolve dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Optional: Add step to run tests here

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A3CBA553D4D54314AEE972C86ABA85D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_154A6E9B291544E8BB69E3AE27FDBCCE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4AAA4B759DC54E28BD668F153688FA95 }}

      - name: Deploy to Azure Functions using Core Tools
        run: |
          func azure functionapp publish flextest5601pyfa2 --python --build-native-deps --no-build
